/**
 * ═══════════════════════════════════════════════════════════════════
 * 🧊 CENSO DE GLOBALES window.* — guardián de la Fase E (tanda 1)
 * ═══════════════════════════════════════════════════════════════════
 *
 * La auditoría 2026-08-03 midió el acoplamiento real del frontend: cientos de
 * asignaciones window.* — estado y funciones compartidos SIN contrato. Es el
 * mecanismo por el que "toco A y se rompe B": cualquier módulo puede leer o
 * pisar cualquier global, y el orden de carga importa.
 *
 * La Fase E los migra a stores/imports por tandas. Esta tanda 1 CONGELA la
 * superficie: 462 claves censadas (LITE — incluye modulos mobile/ y lite/ que main no tiene).
 *
 *   1. FALLA si aparece una clave window.* NUEVA → usa un import o un store
 *      (ya existen 8 en src/stores). Si el puente global está justificado
 *      (onclick del index.html, legacy), explícalo en el PR y censa la clave.
 *   2. FALLA si una clave censada desaparece → bórrala de la lista y
 *      celébralo en el PR: el censo solo puede ENCOGER, nunca crecer.
 *
 * Guardián hermano del censo de puertas de stock del backend
 * (tests/guards/stock-writers-census.test.js de lacaleta-api).
 * Probado por MUTACIÓN al crearlo (regla 5 del CLAUDE.md).
 */

import { readFileSync, readdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname_ = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname_, '..', '..');

// Asignaciones window.X = (no compara ==/===). Misma regex que generó el censo.
const ASSIGN_RE = /window\.([A-Za-z_$][\w$]*)\s*=(?!=)/g;

const CLAVES_CENSADAS = new Set([
    'API',
    'API_CONFIG',
    'Chart',
    'DOM',
    'ErrorHandler',
    'FormProtection',
    'Performance',
    'Validation',
    'XLSX',
    '__albaranExtras',
    '__albaranHints',
    '__analisisRetryPending',
    '__analisisState',
    '__importParsers',
    '__inventarioFlexible',
    '__mlShowPanel',
    '__onboardingChecklistNav',
    '__onboardingChecklistToggle',
    '__onboardingSpotlightClose',
    '__onboardingSpotlightGo',
    '__onboardingSpotlightSkip',
    '__pendingSub',
    '__subscriptionInterceptorInstalled',
    '_alergenosManual',
    '_alertBadgeInterval',
    '_authRedirecting',
    '_chartEscandallo',
    '_editandoPedido',
    '_escandalloActual',
    '_forceRecalcStock',
    '_forecastChart',
    '_forecastTabsInitialized',
    '_planData',
    '_searchResults',
    '_smartOrderGroups',
    '_tokenRefreshInterval',
    '_ventasCache',
    '_ventasPagina',
    'abrirCarrito',
    'abrirDeteccionAlergenosBatch',
    'abrirDossierV24',
    'abrirInformeMensual',
    'abrirManualFormulas',
    'abrirModalEditarPedido',
    'abrirModalNuevoGastoFijo',
    'abrirModalPlato',
    'abrirModalTransferencia',
    'abrirRecuentoInventario',
    'abrirSmartOrder',
    'actualizarAjustePedido',
    'actualizarBadgeCarrito',
    'actualizarBonificacionPedido',
    'actualizarCamposDia',
    'actualizarCamposJornada',
    'actualizarCantidadCarrito',
    'actualizarDashboardExpandido',
    'actualizarItemEdicion',
    'actualizarItemEdicionFmt',
    'actualizarItemRecepcion',
    'actualizarIvaCarrito',
    'actualizarIvaPedidoEdicion',
    'actualizarKPIs',
    'actualizarKPIsDiario',
    'actualizarKPIsPorPeriodo',
    'actualizarLineaMerma',
    'actualizarPrecioSugerido',
    'actualizarPreviewPrecioUnidad',
    'actualizarSimulador',
    'actualizarTotalConIva',
    'addSplit',
    'agregarAlCarrito',
    'agregarIngredientePedido',
    'agregarIngredienteReceta',
    'agregarItemEdicion',
    'agregarLineaMerma',
    'agregarProveedorIngrediente',
    'agregarVarianteReceta',
    'anadirExtraAlbaran',
    'analisisCategoriaFilter',
    'api',
    'apiClient',
    'aplicarAlbaranCant',
    'aplicarAlbaranPrecio',
    'aplicarGatingComidaPersonal',
    'aplicarGatingPlan',
    'aplicarPrecioSugerido',
    'aprobarTransferenciaPendiente',
    'authStore',
    'authToken',
    'autocompletarPrecioEdicion',
    'bcgPagination',
    'bcgScatterChart',
    'borrarTodosHorarios',
    'buscarComidaPersonal',
    'buscarIngredienteParaPedido',
    'calcularCosteReceta',
    'calcularCosteRecetaCompleto',
    'calcularDiasDeStock',
    'calcularForecast',
    'calcularPL',
    'calcularTotalPedido',
    'cambiarEstadoItem',
    'cambiarFiltroAnalisisCategoria',
    'cambiarPaginaIngredientes',
    'cambiarPaginaRecetas',
    'cambiarPaginaVentas',
    'cambiarPeriodoVista',
    'cambiarSemanaDiario',
    'cambiarTab',
    'cambiarVistaDiario',
    'cancelarImportarIngredientes',
    'cancelarImportarPedidos',
    'cancelarImportarProveedores',
    'cancelarImportarRecetas',
    'cancelarImportarVentas',
    'cancelarInventarioMasivo',
    'cargarDatos',
    'cargarGastosFijos',
    'cargarHistorialMermas',
    'cargarIngredientesPedido',
    'cargarIngredientesProveedor',
    'cargarResumenMensual',
    'cargarValoresGastosFijos',
    'cargarVariantesVenta',
    'cerrarCarrito',
    'cerrarConfirmRecuento',
    'cerrarConfirmacion',
    'cerrarCostTracker',
    'cerrarDeteccionAlergenosBatch',
    'cerrarFormGastoFijo',
    'cerrarFormularioGastoFijo',
    'cerrarFormularioIngrediente',
    'cerrarFormularioPedido',
    'cerrarFormularioProveedor',
    'cerrarFormularioReceta',
    'cerrarModalDia',
    'cerrarModalEditarPedido',
    'cerrarModalEmpleado',
    'cerrarModalInvitar',
    'cerrarModalProveedoresIngrediente',
    'cerrarModalRecibirPedido',
    'cerrarModalVariantes',
    'cerrarModalVerPedido',
    'cerrarModalVerProveedor',
    'cerrarRecuento',
    'changeLanguage',
    'chartBebidas',
    'chartMargenCategoria',
    'checkAllIntegrations',
    'checkAuth',
    'checkTransferenciasPendientes',
    'clearChatHistory',
    'closeAlertModal',
    'closeHelpModal',
    'closeModal',
    'cm',
    'comidaPersonalActiva',
    'compararConSemanaAnterior',
    'confirmarCarrito',
    'confirmarDeteccionAlergenosBatch',
    'confirmarEliminacion',
    'confirmarImportarIngredientes',
    'confirmarImportarPedidos',
    'confirmarImportarProveedores',
    'confirmarImportarRecetas',
    'confirmarImportarVentas',
    'confirmarInventarioMasivo',
    'confirmarMermaRapida',
    'confirmarMermasFinal',
    'confirmarMermasMultiples',
    'confirmarRecepcionPedido',
    'confirmarRecuento',
    'confirmarSmartOrder',
    'copiarSemana',
    'currentRestauranteId',
    'currentTenantId',
    'currentUser',
    'dataMaps',
    'datosResumenMensual',
    'debounce',
    'descargarHorarioMensual',
    'descargarPDFReceta',
    'descargarPedidoPDF',
    'descargarPlantillaAlimentos',
    'descargarPlantillaBebidas',
    'descargarPlantillaEscandallo',
    'descargarPlantillaProveedores',
    'descargarPlantillaRecetas',
    'descargarPlantillaStock',
    'diarioSemanaActiva',
    'editandoIngredienteId',
    'editandoPedidoId',
    'editandoProveedorId',
    'editandoRecetaId',
    'editarDia',
    'editarEmpleado',
    'editarGastoFijo',
    'editarIngrediente',
    'editarPrecioProveedor',
    'editarProveedor',
    'editarReceta',
    'editarVariante',
    'eliminarDelCarrito',
    'eliminarEmpleado',
    'eliminarGastoFijo',
    'eliminarIngrediente',
    'eliminarItemEdicion',
    'eliminarLineaMerma',
    'eliminarMerma',
    'eliminarPedido',
    'eliminarProveedor',
    'eliminarProveedorIngrediente',
    'eliminarReceta',
    'eliminarUsuarioEquipo',
    'eliminarVariante',
    'eliminarVenta',
    'emparejarExtraAlbaran',
    'empleados',
    'enviarPedidoWhatsApp',
    'enviarTransferencia',
    'esSuministro',
    'escapeHTML',
    'exportMessageToPDF',
    'exportarAExcel',
    'exportarDiarioExcel',
    'exportarEscandalloReceta',
    'exportarIngredientes',
    'exportarInventario',
    'exportarPDFEscandallo',
    'exportarPedidos',
    'exportarProveedores',
    'exportarRecetas',
    'exportarVentas',
    'fetch',
    'fijarTopeFechaPedido',
    'filtrarComidaPersonal',
    'filtrarDepartamento',
    'filtrarDiasPorSemana',
    'filtrarIngredientesProveedor',
    'filtrarPorCategoria',
    'filtrarPorPeriodo',
    'filtrarRecetasPorCategoria',
    'filtrarRecuentoFamilia',
    'fn',
    'formatCurrency',
    'formatDate',
    'formatDateTime',
    'formatQuantity',
    'formatearFecha',
    'generarHorarioIA',
    'generarPDFIngredientes',
    'generarPDFReceta',
    'gestionarProveedoresIngrediente',
    'gestionarVariantesReceta',
    'getApiBaseUrl',
    'getApiUrl',
    'getAuthState',
    'getAuthUrl',
    'getCurrentLanguage',
    'getDateLocale',
    'getFechaHoy',
    'getFechaHoyFormateada',
    'getIngredientUnitPrice',
    'getIngredients',
    'getOrders',
    'getPeriodoActual',
    'getRangoFechas',
    'getRecipes',
    'getRestaurantName',
    'getRestaurantNameForFile',
    'guardarCambiosStock',
    'guardarDia',
    'guardarEdicionPedido',
    'guardarEmpleado',
    'guardarGastoFijo',
    'guardarGastoFinanzas',
    'guardarIngrediente',
    'guardarPedido',
    'guardarProveedor',
    'guardarReceta',
    'guardarVenta',
    'guardarYSeguirRecuento',
    'hideLoading',
    'horarios',
    'ingredientStore',
    'ingredientes',
    'ingredientesProveedores',
    'inicializarFechaActual',
    'init',
    'initCarrito',
    'initChatWidget',
    'initHorarios',
    'initIntegrations',
    'initLiteMode',
    'initRestaurantSwitcher',
    'initSearchOptimizations',
    'inventarioCompleto',
    'invitarUsuarioEquipo',
    'irAIngredienteDesdeProveedor',
    'irAPaginaIngredientes',
    'isAuthenticated',
    'isLoading',
    'jsPDF',
    'jspdf',
    'loadChart',
    'loadPDF',
    'loadSubscriptionStatus',
    'loadXLSX',
    'logout',
    'marcarPedidoRecibido',
    'marcarProveedorPrincipal',
    'mlAnalisisGetPeriodo',
    'mlAnalisisOmnesRender',
    'mlAnalisisOnRender',
    'mlBcgInfo',
    'mlBreakevenGetSnapshot',
    'mlBreakevenInfo',
    'mlBreakevenRender',
    'mlComputeBeneficioNetoDiario',
    'mlGastosOperativosInfo',
    'mlHtmlPLMovil',
    'mlNuevoPedido',
    'mlOmnesInfo',
    'mlPreviewPrecioProveedor',
    'mlRecibirAlbaran',
    'mlSumaGastosOperativos',
    'mlVolverAPedir',
    'mostrarCalculadoraFormato',
    'mostrarCostTracker',
    'mostrarForgotPassword',
    'mostrarFormularioIngrediente',
    'mostrarFormularioPedido',
    'mostrarFormularioProveedor',
    'mostrarFormularioReceta',
    'mostrarLogin',
    'mostrarModalConfirmarMermas',
    'mostrarModalImportarIngredientes',
    'mostrarModalImportarPedidos',
    'mostrarModalImportarProveedores',
    'mostrarModalImportarRecetas',
    'mostrarModalImportarVentas',
    'mostrarModalInventarioMasivo',
    'mostrarModalInvitar',
    'mostrarModalMermaRapida',
    'mostrarRegistro',
    'mountActionDropdowns',
    'nuevoEmpleado',
    'omnesDescartar',
    'omnesIr',
    'onIngredientePedidoChange',
    'openInfoTab',
    'openModal',
    'openTabHelp',
    'ordenarComidaPersonal',
    'orderStore',
    'pedidoRecibiendoId',
    'pedidoStep',
    'pedidoViendoId',
    'pedidos',
    'plComidaPersonalPorDia',
    'plCostesPorDia',
    'plGastosFijosDia',
    'plIngresosPorDia',
    'plMermasPorDia',
    'plPersonalExtraPorDia',
    'planPermiteTab',
    'preguntarAOmnes',
    'procesarArchivoIngredientes',
    'procesarArchivoInventario',
    'procesarArchivoPedidos',
    'procesarArchivoProveedores',
    'procesarArchivoRecetas',
    'procesarArchivoVentas',
    'procesarFotoMerma',
    'procesarFotoMermaInput',
    'proveedores',
    'proyeccionConsumo',
    'quitarDia',
    'recetas',
    'recetasVariantes',
    'rechazarTransferenciaPendiente',
    'recipeStore',
    'refrescarBadgeOmnes',
    'refreshOnboardingChecklist',
    'refreshOnboardingSpotlight',
    'removeSplit',
    'renderBCGPage',
    'renderChatAddonCard',
    'renderForecastChart',
    'renderMenuEngineeringUI',
    'renderMobileHome',
    'renderPersonalExtra',
    'renderRentabilidadPage',
    'renderTablaSplits',
    'renderizarAnalisis',
    'renderizarBalance',
    'renderizarBusqueda',
    'renderizarComidaPersonal',
    'renderizarConfigComidaPersonal',
    'renderizarEquipo',
    'renderizarGastosFijosDinamicos',
    'renderizarIngredientes',
    'renderizarInteligencia',
    'renderizarInventario',
    'renderizarPedidos',
    'renderizarProveedores',
    'renderizarRecetas',
    'renderizarTransferenciasEntrantes',
    'renderizarVentas',
    'rentabilidadPage',
    'repetirPedido',
    'revenueChartInstance',
    'revisarRecuento',
    'safeNumber',
    'saleStore',
    'seguirComprando',
    'seleccionarIngredienteParaPedido',
    'semanaAnterior',
    'semanaSiguiente',
    'setConteoRecuento',
    'setPersonalQtyEdicion',
    'setPersonalQtyEdicionFmt',
    'setupYieldSlider',
    'showAlertModal',
    'showError',
    'showLoading',
    'showSubscriptionModal',
    'showSuccess',
    'showToast',
    'stockRealCache',
    'stopTokenRefresh',
    'stores',
    'sugerirAlergenosPorNombre',
    'supplierStore',
    't',
    'tabActual',
    'tenantKey',
    'tenantStorage',
    'toggleChat',
    'toggleComidaPersonal',
    'toggleIngredienteActivo',
    'togglePersonalEdicion',
    'toggleSmartItem',
    'toggleTurno',
    'translateHTML',
    'uiStore',
    'updateAlertBadge',
    'updateChatUsageBadge',
    'updateDifferenceCell',
    'updateSmartQty',
    'updateSplitAmount',
    'updateSplitNote',
    'updateSplitReason',
    'vaciarCarrito',
    'ventas',
    'verDetallesPedido',
    'verEscandallo',
    'verEvolucionPrecio',
    'verHistorialMermas',
    'verMasHistorial',
    'verProveedorDetalles',
    'volverALogin',
]);

function walk(dir) {
    return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
        const p = join(dir, e.name);
        if (e.isDirectory()) return ['node_modules', '__tests__'].includes(e.name) ? [] : walk(p);
        return e.name.endsWith('.js') && !e.name.endsWith('.test.js') ? [p] : [];
    });
}

function clavesActuales() {
    const keys = new Set();
    for (const f of walk(SRC)) {
        const s = readFileSync(f, 'utf8');
        let m;
        while ((m = ASSIGN_RE.exec(s))) keys.add(m[1]);
    }
    return keys;
}

describe('🧊 Censo de globales window.* (Fase E tanda 1)', () => {
    const actuales = clavesActuales();

    it('ninguna clave global NUEVA fuera del censo', () => {
        const nuevas = [...actuales].filter((k) => !CLAVES_CENSADAS.has(k)).sort();
        if (nuevas.length) {
            throw new Error(
                'Clave(s) window.* NUEVA(S): ' + nuevas.join(', ') + '.\n' +
                'La superficie global solo puede ENCOGER. Usa un import o un store ' +
                '(src/stores). Si el puente global está justificado (onclick del ' +
                'index.html, legacy), explícalo en el PR y añade la clave al censo.'
            );
        }
        expect(nuevas).toEqual([]);
    });

    it('ninguna clave censada ha desaparecido sin actualizar el censo', () => {
        const migradas = [...CLAVES_CENSADAS].filter((k) => !actuales.has(k)).sort();
        if (migradas.length) {
            throw new Error(
                'Clave(s) censada(s) que YA NO se asignan: ' + migradas.join(', ') + '.\n' +
                'Bórralas de CLAVES_CENSADAS y celébralo en el PR — el censo encoge.'
            );
        }
        expect(migradas).toEqual([]);
    });

    it('marcador de progreso: 462 claves (2026-08-04, tanda 1)', () => {
        expect(actuales.size).toBe(CLAVES_CENSADAS.size);
    });
});
